export const trials = [
  "Crystal",
  "Genesis",
  "Glass",
  "Riser",
  "Solar",
  "Vestibule",
  "Celsius",
  "Circulation",
  "Flow",
  "Martyr",
  "Neon Bold",
  "Sawdust",
  "Ascension",
  "Faith",
  "Gale",
  "Grip",
  "Thread",
  "Umbrel",
  "Depot",
  "Flame",
  "Ironsing",
  "Monoxide",
  "Rust Belt",
  "Wisp",
] as const

export const plats = {
  "Crystal": 10.5,
  "Genesis": 12.5,
  "Glass": 12.5,
  "Riser": 10.75,
  "Solar": 18,
  "Vestibule": 10.5,
  "Celsius": 12,
  "Circulation": 14,
  "Flow": 16.5,
  "Martyr": 12.5,
  "Neon Bold": 25,
  "Sawdust": 16.5,
  "Ascension": 12,
  "Faith": 15,
  "Gale": 8.25,
  "Grip": 17,
  "Thread": 14,
  "Umbrel": 23,
  "Depot": 19.5,
  "Flame": 13.5,
  "Ironsing": 17.5,
  "Monoxide": 14.5,
  "Rust Belt": 18.5,
  "Wisp": 13,
}

export const bronze = {
  "Crystal": 25,
  "Genesis": 70,
  "Glass": 30,
  "Riser": 25,
  "Solar": 40,
  "Vestibule": 24,
  "Celsius": 25,
  "Circulation": 35,
  "Flow": 32,
  "Martyr": 35,
  "Neon Bold": 40,
  "Sawdust": 40,
  "Ascension": 25,
  "Faith": 30,
  "Gale": 15,
  "Grip": 35,
  "Thread": 25,
  "Umbrel": 35,
  "Depot": 50,
  "Flame": 30,
  "Ironsing": 29,
  "Monoxide": 27,
  "Rust Belt": 35,
  "Wisp": 22,
}

export type TrialName = (typeof trials)[number]
