import test from "node:test"
import assert from "node:assert/strict"
import {
  COMPILATION_STALE_AFTER_SECONDS,
  COMPILATION_YOUTUBE_DESCRIPTION,
  compilationYouTubeDescription,
  compilationYouTubeTitle,
  formatWrHeldFor,
  compilationAsOf,
  compilationObjectKey,
  compilationTitle,
  isCompilationStale,
} from "../compilations"

test("the monthly cron run is titled after the month that just ended", () => {
  const firstOfNovember = new Date(Date.UTC(2026, 10, 1, 0, 0, 5))

  assert.equal(compilationTitle(firstOfNovember, "scheduled"), "World Records — October 2026")
  assert.equal(compilationAsOf(firstOfNovember, "scheduled"), "October 31, 2026")
})

test("the January cron run wraps back to December of the previous year", () => {
  const firstOfJanuary = new Date(Date.UTC(2027, 0, 1, 0, 0, 5))

  assert.equal(compilationTitle(firstOfJanuary, "scheduled"), "World Records — December 2026")
  assert.equal(compilationAsOf(firstOfJanuary, "scheduled"), "December 31, 2026")
  assert.equal(compilationObjectKey(firstOfJanuary, "scheduled", "abc"), "compilations/wr-compilation-2026-12-abc.mp4")
})

test("a manual render is titled after the current month", () => {
  const midOctober = new Date(Date.UTC(2026, 9, 14, 12))

  assert.equal(compilationTitle(midOctober, "manual"), "World Records — October 2026")
  assert.equal(compilationAsOf(midOctober, "manual"), "October 14, 2026")
  assert.equal(compilationObjectKey(midOctober, "manual", "xyz"), "compilations/wr-compilation-2026-10-xyz.mp4")
})

test("February's last day accounts for leap years", () => {
  assert.equal(compilationAsOf(new Date(Date.UTC(2028, 2, 1)), "scheduled"), "February 29, 2028")
  assert.equal(compilationAsOf(new Date(Date.UTC(2027, 2, 1)), "scheduled"), "February 28, 2027")
})

test("an in-progress compilation only counts as stale after the renderer's own timeout", () => {
  const now = 1_000_000

  assert.equal(isCompilationStale(now - 60, now), false)
  assert.equal(isCompilationStale(now - COMPILATION_STALE_AFTER_SECONDS - 1, now), true)
})

test("the YouTube title always names the month that just ended", () => {
  assert.equal(compilationYouTubeTitle(new Date(Date.UTC(2026, 9, 1, 0, 0, 5))), "September WRs Compilation | Parkour Reborn")
  assert.equal(compilationYouTubeTitle(new Date(Date.UTC(2026, 9, 14, 12))), "September WRs Compilation | Parkour Reborn")
  assert.equal(compilationYouTubeTitle(new Date(Date.UTC(2027, 0, 1))), "December WRs Compilation | Parkour Reborn")
})

test("the YouTube description is the fixed text", () => {
  assert.equal(
    COMPILATION_YOUTUBE_DESCRIPTION,
    "Autogenerated by wasans (https://wasans.tully.sh)\n\nSee up to date list of wrs here:\nhttps://wasans.tully.sh/wrs"
  )
})

test("the YouTube description lists a chapter per trial, the first at 0:00", () => {
  const chapters = [
    { start: 0, label: "Intro" },
    { start: 3, label: "Crystal - jahz 7.553" },
    { start: 14.6, label: "Genesis - Tully Aviv 6.390" },
    { start: 75, label: "Glass - x 12.000" },
  ]

  assert.equal(
    compilationYouTubeDescription(chapters),
    `${COMPILATION_YOUTUBE_DESCRIPTION}\n\n0:00 Crystal - jahz 7.553\n0:14 Genesis - Tully Aviv 6.390\n1:15 Glass - x 12.000`
  )
})

test("fewer than three trials means no chapters (YouTube would ignore them)", () => {
  assert.equal(
    compilationYouTubeDescription([{ start: 0, label: "Intro" }, { start: 3, label: "Crystal - jahz 7.553" }]),
    COMPILATION_YOUTUBE_DESCRIPTION
  )
})

test("WR age is whole days since the record was set", () => {
  const day = 86_400
  const now = 1_000_000_000

  assert.equal(formatWrHeldFor(now - 259 * day - 5, now), "259 days")
  assert.equal(formatWrHeldFor(now - 12 * day, now), "12 days")
  assert.equal(formatWrHeldFor(now - day - 1, now), "1 day")
  assert.equal(formatWrHeldFor(now - 3600, now), "0 days")
  // A clock skew can't produce a negative age.
  assert.equal(formatWrHeldFor(now + 60, now), "0 days")
})
